#!/usr/bin/env julia
# Turn raw `--trace-compile` output into BonitoAgents/src/precompile_statements.jl.
#
# Run in the BonitoAgents env so statements can be verified:
#   julia --project=BonitoAgents BonitoAgentsApp/precompile/generate.jl [trace-dir...]
#
# Approach borrowed from dev/TracePrecompiles: the emitted file is a self-contained
# submodule that
#   * binds every referenced module via `require(PkgId(uuid, name))` — they're all
#     loaded transitively, so no new deps, and PkgId/uuid is exact,
#   * wraps each call in a `@precompile` macro that only fires during precompilation
#     and try/catches at @debug. That guard wraps the *argument construction* too,
#     so an unstable anonymous-closure gensym (`var"#84#85"`) just SKIPS at @debug
#     instead of breaking the build — which is why we can keep the closures.
# We still verify each statement at generation time (drop the ones that don't even
# resolve here) and report what was dropped — no silent loss.

const DEFAULT_DIR = joinpath(@__DIR__, "traces")
const OUT = normpath(joinpath(@__DIR__, "..", "..", "BonitoAgents", "src", "precompile_statements.jl"))
const TARGET = "BonitoAgents"   # the package this file is included into; bind it to
                                # the already-loading parent, never `require` (self-deadlock)
const REJECT = ("Main.", "TestKit", "TestHelpers", ".TH.", "Workspace", "Revise",
                "Base.Compiler", "Core.Compiler", "ElectronCall")
isrejected(l) = any(s -> occursin(s, l), REJECT)

function candidates(args)
    paths = isempty(args) ? [DEFAULT_DIR] : args
    files = String[]
    for p in paths
        if isdir(p); append!(files, filter(f -> endswith(f, ".jl"), readdir(p; join=true)))
        elseif isfile(p); push!(files, p)
        else; @warn "not found" path=p end
    end
    isempty(files) && error("no trace files found")
    out = Set{String}()
    for f in files, raw in eachline(f)
        l = strip(raw)
        startswith(l, "precompile(Tuple{") || continue
        (occursin("#=", l) || isrejected(l)) && continue
        push!(out, l)
    end
    sort!(collect(out)), files
end

cands, files = candidates(ARGS)

# ── bind every referenced module into a verification scope ───────────────────
using BonitoAgents
import Bonito, HTTP

lm(n) = (for (id, m) in Base.loaded_modules; String(id.name) == n && return m end; nothing)
# bare submodule names the trace emits (no uuid — bound from their parent)
const NESTED = Dict(:Iterators=>:(Base.Iterators), :Order=>:(Base.Order), :Broadcast=>:(Base.Broadcast),
                    :Sort=>:(Base.Sort), :CoreLogging=>:(Base.CoreLogging), :Docs=>:(Base.Docs),
                    :Filesystem=>:(Base.Filesystem), :StackTraces=>:(Base.StackTraces),
                    :Threads=>:(Base.Threads), :DOM=>:(Bonito.DOM), :HTTPServer=>:(Bonito.HTTPServer),
                    :WebSockets=>:(HTTP.WebSockets))

rootof(l) = (m = match(r"([A-Za-z_][A-Za-z0-9_]*)\.", l); m === nothing ? "?" : m.captures[1])
roots = Set(rootof(s) for s in cands)

const SCOPE = Module(:PrecompileScope)
pkg_binds = Pair{String,String}[]   # name => "require(PkgId(UUID(\"...\"), \"name\"))"
nested_binds = Pair{Symbol,Expr}[]
for r in roots
    sym = Symbol(r)
    if haskey(NESTED, sym)
        try; Core.eval(SCOPE, :(const $sym = $(NESTED[sym]))); push!(nested_binds, sym => NESTED[sym]); catch; end
    else
        m = lm(r); m === nothing && continue
        pid = Base.PkgId(m); pid.uuid === nothing && continue
        try
            Core.eval(SCOPE, :(const $sym = $m))
            expr = r == TARGET ? "parentmodule(@__MODULE__)" :
                                 "require(PkgId(UUID(\"$(pid.uuid)\"), \"$r\"))"
            push!(pkg_binds, r => expr)
        catch
        end
    end
end

# ── verify each statement (keep ones that resolve; report drops) ─────────────
kept = String[]; nfalse = 0; failroot = Dict{String,Int}()
for s in cands
    try
        Core.eval(SCOPE, Meta.parse(s)) === true ? push!(kept, s) : (nfalse += 1)
    catch
        failroot[rootof(s)] = get(failroot, rootof(s), 0) + 1
    end
end

# ── emit a guarded self-contained submodule ──────────────────────────────────
open(OUT, "w") do io
    println(io, "# AUTO-GENERATED by BonitoAgentsApp/precompile/generate.jl — do not edit.")
    println(io, "# $(length(kept)) precompile statements from $(length(files)) trace file(s),")
    println(io, "# captured from the e2e suite. Approach: dev/TracePrecompiles.")
    println(io, "module PrecompileStatements")
    println(io, "using Base: UUID, PkgId, require")
    println(io, """
    # Only fire during precompilation, and try/catch around the WHOLE call so a
    # statement whose argument no longer resolves (e.g. an anonymous-closure gensym
    # that shifted on recompile) skips at @debug instead of failing the build.
    macro precompile(args)
        ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
        return quote
            try
                precompile(\$(esc(args)))
            catch e
                @debug "precompile skipped" exception = e
            end
        end
    end""")
    println(io)
    for (name, expr) in sort(pkg_binds; by=first); println(io, "const $name = $expr"); end
    for (sym, ex) in sort(nested_binds; by=first); println(io, "const $sym = $ex"); end
    println(io)
    for s in kept; println(io, "@", s); end
    println(io, "end # module PrecompileStatements")
end

println("kept=$(length(kept))  dropped_false=$nfalse  dropped_unresolved=$(sum(values(failroot); init=0))  of $(length(cands))")
isempty(failroot) || println("  unresolved by root: ", sort(collect(failroot); by=last, rev=true))
println("wrote ", OUT)
