# Single source of truth for server-side state. Replaces 14 module-level
# globals (WORKERS, PROJECTS, PENDING_*, STATE_VERSION, etc.) with one
# `ServerState` struct constructed in `serve()` and threaded through every
# route handler / dashboard / chat closure.
#
# Why one struct: each `serve()` call is one server. Module globals made
# multi-instance testing impossible and let stale observables from a
# re-rendered form leak into a new render through the shared dict.

mutable struct WorkerInfo
    # Stable per-install identity (UUID generated by the worker on first run
    # and persisted to ~/.local/share/bonitoteam-worker/worker_id). This is
    # the dict key in `ServerState.workers` so a worker survives hostname /
    # IP / display-name changes — moving a laptop between Wi-Fi networks,
    # or two installs that both default to "localhost", no longer collide.
    worker_id::String
    name::String                       # display name (mutable; user-renameable)
    # Short tag (1–4 chars; emoji ok) shown as `[XX]` in chat/project labels
    # so the user can tell at a glance which machine a chat lives on.
    # `nothing` → derive from `name` via `derive_initials`.
    initials::Union{String,Nothing}
    url::String                        # ws://host:port
    secret::String
    ssh_target::Union{String,Nothing}  # for ssh-based rsync: "user@host". nothing → local rsync
    # discovered via probe
    hostname::String
    home::String
    mcp_path::String                   # MCP launch command on worker (the julia binary)
    mcp_args::Vector{String}           # MCP launch args on worker (--project=…, -e …)
    projects_root::String              # rsync destination root on worker
    # runtime
    status::Symbol                     # :unknown, :online, :offline
    last_check::DateTime
end

mutable struct ProjectInfo
    id::String                         # short uuid
    name::String                       # display name + dir name (server + worker)
    # FK into `ServerState.workers` — stores the worker's stable UUID, NOT
    # its (mutable) display name. Old projects.json entries that still carry
    # a display name string in the `worker_name` field get migrated lazily
    # on the next worker connect (see handle_worker_control).
    worker_id::String
    server_path::String                # canonical copy on server (= state.working_dir/name)
    worker_path::String                # mirrored copy on worker (= worker.projects_root/name)
    created::DateTime
    # At most one active ACP session per project. Acquired when
    # ensure_project_session! brings up the ChatModel; released automatically
    # when the bound worker's control WS drops (the claude process is gone
    # with it). Worker-only-write model means there's no checksum/divergence
    # state — anything claude writes on the worker auto-flows back to the
    # server, the operator never edits server_path.
    locked_by::Union{String,Nothing}      # worker_name when active, else nothing
    locked_at::Union{DateTime,Nothing}
    # :unsynced (default for worker-imported projects) — server has no copy.
    # :syncing — a librsync transfer is in progress.
    # :synced — last librsync transfer completed successfully; server has a copy.
    # :stale — was synced once but content has likely diverged since.
    # Persistence: only :unsynced vs :synced is durable; :syncing always resets
    # to :stale on restart so a crash mid-sync doesn't leave a wrong "synced".
    backup_status::Symbol
    last_sync_at::Union{DateTime,Nothing}
    # Set when the project was imported from an existing claude-agent-acp
    # session — the .jsonl basename in ~/.claude/projects/<encoded>/ on the
    # worker. start_session(::WorkerTransport) uses session/load with this ID to bring
    # the conversation history back to where claude left off; nothing → fresh
    # session/new. Persisted so server restarts still resume.
    resume_session_id::Union{String,Nothing}
    # If set, the chat fires this prompt as the first user message the next
    # time it brings up an ACP session — used by the "From GitHub" template
    # to seed "fix this issue" / "review this PR" without the operator having
    # to retype it. Cleared (and persisted as nothing) once the prompt has
    # been delivered, so a session restart doesn't re-fire.
    auto_prompt::Union{String,Nothing}
    # Editable human-readable title for the chat, shown in the sidebar and
    # project card. Auto-set from the first meaningful user prompt in
    # `send_message!` if it's still `nothing`; a user edit pins it. `nothing`
    # → the sidebar/card falls back to `name` (folder basename).
    title::Union{String,Nothing}
end

ProjectInfo(id, name, worker_id, server_path, worker_path, created) =
    ProjectInfo(id, name, worker_id, server_path, worker_path, created,
                nothing, nothing, :unsynced, nothing, nothing, nothing, nothing)

# Back-compat positional WorkerInfo constructor — keeps the pre-`initials`
# call shape working for tests / fixtures that build a WorkerInfo by hand.
# New code that wants a custom tag uses the full 13-arg form (or sets
# `.initials` directly).
WorkerInfo(worker_id, name, url, secret, ssh_target, hostname, home,
           mcp_path, mcp_args, projects_root, status, last_check) =
    WorkerInfo(worker_id, name, nothing, url, secret, ssh_target, hostname, home,
               mcp_path, mcp_args, projects_root, status, last_check)

"""
    ServerState

Everything one running BonitoTeam server needs. Constructed in `serve()`
and captured by route closures, dashboard / chat apps, and worker control
handlers. Five things deserve a paragraph each:

- `pending_rpcs` collapses what used to be five separate dicts (one per
  RPC type). The keys are uuids, so cross-RPC-type collisions can't happen,
  and the unified shape removes a lot of duplicated bookkeeping.
- `workers` and `projects` are themselves Observables wrapping the live
  Dicts. Mutators do in-place updates and then `notify(state.projects)`
  (or `state.workers`) to fan out to listeners. Sidebar / dashboard
  consumers `map(state.projects) do projects … end` — they get the
  current Dict by value, so adding a worker doesn't redraw the project
  list and vice versa. There's no separate version-int sentinel: the
  data IS the change signal.
- `worker_control_ws` keys workers by name (the same key as `workers`).
- `srv` is filled in after `Bonito.Server` is constructed (chicken-and-egg:
  the dashboard app captures the state, but the server constructor takes
  the dashboard).
- `worker_secret` is the auth token every worker presents on its hello
  frame; same secret across all workers, baked into the install script.
"""
mutable struct ServerState
    # Convention: every shared-state struct's first field is its lock.
    # Bonito App bodies run on different threads per browser tab and the
    # WS handler / RPC pumps can mutate the dicts at any time, so all
    # multi-field reads/writes go through `lock(state.lock) do … end`.
    # Per-session views are produced by `Base.copy(state, session)` (below)
    # which SHARES this lock with the parent — sessions cooperate, they
    # don't each get their own mutex. See .claude/skills/bonito/SKILL.md
    # § "Thread-safe shared state".
    lock :: ReentrantLock

    # Disk paths (immutable after construction)
    state_dir   :: String
    working_dir :: String
    # Auth
    worker_secret :: String
    # Live Bonito server (set by serve() after construction)
    srv :: Union{Bonito.Server,Nothing}

    # Persisted state, wrapped in Observables so consumers can `map` them
    # directly (no sentinel version-int). Mutators do in-place updates and
    # then `notify(state.workers)` / `notify(state.projects)` to fan out
    # to listeners. The .{} access forms — `state.projects[][id]`,
    # `values(state.projects[])`, etc. — are the price for collection-
    # level reactivity, but they're mechanical and the win is that the
    # sidebar (project-only) ignores worker churn and the worker cards
    # ignore project churn.
    #
    # SHARED parents: App bodies must not `map(state.projects)` directly.
    # Take `view = copy(state, session)` and `map(view.projects)` so each
    # session subscribes to its own connected child Observable (auto-GC'd
    # on session close).
    workers  :: Observable{Dict{String,WorkerInfo}}
    projects :: Observable{Dict{String,ProjectInfo}}

    # Runtime caches (not persisted). One ChatModel per project, lazily built
    # the first time the project's chat is opened or the worker reconnects;
    # holds the live ACP client and message store. The unified app's main
    # panel pulls the model from here when a project icon is selected.
    chat_models :: Dict{String,Any}   # id → ChatModel

    # Bumped (via `notify_chats!`) whenever `chat_models` gains or loses an
    # entry. `chat_models` is a plain Dict (not an Observable), but the
    # left-hand "active chats" sidebar needs to re-render when a chat opens or
    # closes — so it `map`s this signal and snapshots the live keys. The value
    # is meaningless; only the notification matters.
    chat_signal :: Observable{Int}

    # Live worker connections (name → HTTP.WebSocket)
    worker_control_ws :: Dict{String,Any}

    # Pending request_id → channel handoffs for every RPC type. Channel{Any}
    # because the answer shape varies (WS for handoff, Dict for rpc result).
    pending_rpcs :: Dict{String,Channel{Any}}

    # Persisted result of "discover Claude Code sessions" per worker:
    # worker_id → Vector of session dicts (session_id, path, first_prompt,
    # last_used, running, kind, …). Backs the dashboard's persistent
    # folder→threads browser so the tree survives a server restart without
    # re-scanning (refresh via the per-worker Rescan button). Saved to
    # `discovered.json`; mutated in place + `notify`d like `projects`.
    discovered :: Observable{Dict{String,Vector{Dict{String,Any}}}}
end

"""
    ServerState(; state_dir, working_dir, worker_secret) → ServerState

Construct a fresh state, loading workers + projects from `state_dir`
(`workers.json`, `projects.json`). `working_dir` is created if missing.
"""
function ServerState(; state_dir::String,
                       working_dir::String,
                       worker_secret::String)
    mkpath(working_dir)
    s = ServerState(
        ReentrantLock(),
        state_dir, working_dir, worker_secret,
        nothing,
        Observable(Dict{String,WorkerInfo}()),    # workers
        Observable(Dict{String,ProjectInfo}()),   # projects
        Dict{String,Any}(),                       # chat_models
        Observable(0),                            # chat_signal
        Dict{String,Any}(),                       # worker_control_ws
        Dict{String,Channel{Any}}(),              # pending_rpcs
        Observable(Dict{String,Vector{Dict{String,Any}}}()),  # discovered
    )
    load_workers!(s)
    load_projects!(s)
    load_discovered!(s)
    return s
end

# Per-session view of `state`. SHARES the lock, dicts, and the live `srv`
# field with the parent — sessions cooperate on the same workers/projects/
# chat_models tables and the same lock. Each Observable field is bridged
# via `map(identity, session, obs)`: that produces a connected child
# AND registers the parent→child callback on `session.deregister_callbacks`,
# so when the tab closes the bridge tears down automatically. (Plain
# `copy(obs)` would leak the callback on the parent forever.)
#
# Use `view = copy(state, session)` at the top of every `App() do session ... end` body.
function Base.copy(s::ServerState, session::Bonito.Session)
    lock(s.lock) do
        ServerState(
            s.lock,
            s.state_dir, s.working_dir, s.worker_secret,
            s.srv,
            map(identity, session, s.workers),
            map(identity, session, s.projects),
            s.chat_models,
            map(identity, session, s.chat_signal),
            s.worker_control_ws,
            s.pending_rpcs,
            map(identity, session, s.discovered),
        )
    end
end

workers_file(s::ServerState)    = joinpath(s.state_dir, "workers.json")
projects_file(s::ServerState)   = joinpath(s.state_dir, "projects.json")
discovered_file(s::ServerState) = joinpath(s.state_dir, "discovered.json")

"""
    derive_initials(name) -> String

Two-character tag derived from a worker's display name. `"Mini-Server"` →
`"MS"`, `"HP Laptop"` → `"HL"`, `"desktop"` → `"DE"`. Used as the auto
fallback when `WorkerInfo.initials` is `nothing`. Whitespace / `-` / `_`
are treated as word separators; for a single word we take the first two
non-space characters and uppercase them; if even that's empty we return
`"??"` so something always renders.
"""
function derive_initials(name::AbstractString)
    parts = filter(!isempty, split(String(name), r"[\s_\-]+"))
    if length(parts) >= 2
        return uppercase(string(first(parts[1]), first(parts[2])))
    elseif length(parts) == 1
        s = parts[1]
        length(s) >= 2 ? uppercase(string(s[1:2])) : uppercase(s) * "?"
    else
        return "??"
    end
end

worker_initials(w::WorkerInfo) =
    w.initials === nothing || isempty(w.initials) ? derive_initials(w.name) :
                                                    w.initials

project_display_title(p::ProjectInfo) =
    p.title === nothing || isempty(p.title) ? p.name : p.title

# Setting an Observable propagates to the browser via Bonito's WebSocket;
# if a session is broken (e.g. a stale tab whose hashed asset URLs went 404
# after a redeploy), Bonito surfaces that as a JSException from the
# observable update. We don't want a stale UI tab to break server-side
# operations, so we swallow + log via these helpers instead of letting the
# JSException unwind a server thread.

# Best-effort `obs[] = val`. Use for plain Observable updates.
function safe_set!(obs::Observable, val)
    try
        obs[] = val
    catch e
        @debug "safe_set!: observable propagation failed (likely stale browser session)" exception=e
    end
    return nothing
end

# Errors a stale browser session raises when we push an update to it: a Bonito
# JSException (hashed asset 404 after redeploy), or a transport-level failure on
# a half-dead socket. These are the "this one tab is gone" signals — NOT a bug in
# our code — so `safe_notify!` tolerates them per-listener; anything else
# rethrows (a real error must not be hidden, T6).
is_stale_session_error(e) =
    e isa Bonito.JSException ||
    e isa Base.IOError ||
    e isa HTTP.WebSockets.WebSocketError ||
    e isa EOFError ||
    (e isa ArgumentError && occursin("closed", lowercase(e.msg)))

# Best-effort `notify(obs)` — fires listeners without changing the value. Use
# after in-place mutation of `state.workers[]` / `state.projects[]`.
#
# `Base.notify(::Observable)` aborts at the FIRST throwing listener, so one stale
# tab would starve every later-registered tab (T6). Instead we fire each listener
# in its own try: a stale-session error deregisters just that dead listener (so
# it stops costing us on every future notify) and we keep going; a real error is
# rethrown so it surfaces. We iterate a SNAPSHOT of the listener list because we
# mutate it (deregistration) and a listener may itself (de)register. The
# `Consume` short-circuit semantics of `Base.notify` are preserved.
# `Bonito.Observables` is the Observables module re-reachable through Bonito
# (which `using`s it) — Observables isn't a direct dep of this package.
function safe_notify!(obs::Observable)
    val = obs[]
    dead = Any[]
    for (_, f) in copy(obs.listeners)
        try
            result = Base.invokelatest(f, val)
            # Preserve `Base.notify`'s behaviour: a listener returning
            # `Consume(true)` stops propagation to lower-priority listeners.
            if result isa Bonito.Observables.Consume && result.x
                break
            end
        catch e
            if is_stale_session_error(e)
                @warn "safe_notify!: dropping a stale browser-session listener" errtype=typeof(e)
                push!(dead, f)
            else
                rethrow()
            end
        end
    end
    for f in dead
        Bonito.Observables.off(obs, f)
    end
    return nothing
end

# Signal that `chat_models` changed (a chat opened or closed) so the active-
# chats sidebar re-renders. Call with the SAME state the mutation used: a
# worker handler / async task holds the parent state (fans out to every
# session's bridged `chat_signal`); a UI handler holds its per-session view
# (updates that session). Mirrors how the existing `safe_notify!(state.projects)`
# calls are threaded.
notify_chats!(s::ServerState) = safe_notify!(s.chat_signal)

# ── Persistence ───────────────────────────────────────────────────────────
# Atomic JSON write: serialise to a UNIQUE sibling temp file first, then rename
# into place. `rename(2)` on the same filesystem is atomic, so a crash mid-save
# can leave only the old file or only the new — never a half-written file.
#
# The temp name is per-call unique (`tempname(dir; cleanup=false)`) rather than a
# fixed `path * ".tmp"`: two concurrent saves of the same target sharing one
# fixed tmp path would have the second writer truncate the first's tmp under it,
# and one `mv` could then rename a half-written file into place (T2). A unique
# tmp per writer keeps each save's bytes disjoint; the final `mv` is still atomic
# last-writer-wins. The savers also serialise under `state.lock` (below), so in
# practice concurrent same-target writes don't happen — this is belt-and-braces.
function atomic_write_json(path::String, data)
    dir = dirname(path)
    mkpath(dir)
    tmp = tempname(dir; cleanup = false)
    try
        open(tmp, "w") do io
            JSON.print(io, data, 2)
        end
        mv(tmp, path; force = true)
    catch
        # Don't leave a stray temp file behind if the write or rename failed.
        try
            rm(tmp; force = true)
        catch cleanup_err
            @debug "atomic_write_json: could not remove temp file" tmp exception = cleanup_err
        end
        rethrow()
    end
end

# Read JSON with corruption tolerance: if the file is truncated/garbled (e.g.
# from a crash before atomic_write_json existed, or a manual edit gone wrong),
# log a warning, move it aside as `<file>.bad`, and continue with empty state.
# We'd rather lose worker/project metadata than refuse to start the server.
function load_json_tolerant(path::String, label::String)
    isfile(path) || return nothing
    try
        return JSON.parsefile(path)
    catch e
        bad = path * ".bad-" * Dates.format(now(UTC), "yyyymmddTHHMMSS")
        # mv with force=true rarely fails; if it does (permission issue,
        # cross-fs EXDEV), let the @warn cover both the parse-failure
        # AND the mv-failure so we don't silently lose visibility.
        try
            mv(path, bad; force = true)
        catch mv_e
            @warn "$label: failed to move aside corrupted file" path bad exception=mv_e
            bad = "(rename failed)"
        end
        @warn "$label: failed to parse — moved aside, starting empty" path bad exception=e
        return nothing
    end
end

# `state.lock` is a ReentrantLock, so a caller that already holds it (e.g. a
# worker-registration critical section) re-enters harmlessly. We snapshot the
# serialised rows UNDER the lock so an unlocked saver can't iterate
# `values(s.workers[])` while a locked writer mutates the dict (T2), then write
# the file outside the lock isn't necessary — the write is fast and keeping it
# inside also serialises concurrent saves of the SAME file so they can't race
# the rename.
function save_workers!(s::ServerState)
    lock(s.lock) do
        data = [Dict("worker_id" => w.worker_id,
                     "name" => w.name, "initials" => w.initials,
                     "url" => w.url, "secret" => w.secret,
                     "ssh_target" => w.ssh_target,
                     "hostname" => w.hostname, "home" => w.home,
                     "mcp_path" => w.mcp_path, "mcp_args" => w.mcp_args,
                     "projects_root" => w.projects_root)
                for w in values(s.workers[])]
        atomic_write_json(workers_file(s), data)
    end
end

function load_workers!(s::ServerState)
    raw = load_json_tolerant(workers_file(s), "workers.json")
    raw === nothing && return
    for d in raw
        try
            # Migration: workers.json from before the worker_id field was
            # introduced has only `name`. Use the legacy display name as
            # a stand-in worker_id so existing project FKs keep resolving;
            # the next worker reconnect will overwrite this with the real
            # UUID from the worker's hello frame.
            wid = String(get(d, "worker_id", d["name"]))
            init_raw = get(d, "initials", nothing)
            initials = (init_raw === nothing || (init_raw isa AbstractString && isempty(init_raw))) ?
                       nothing : String(init_raw)
            w = WorkerInfo(wid, d["name"], initials,
                           d["url"], d["secret"],
                           get(d, "ssh_target", nothing),
                           get(d, "hostname", ""), get(d, "home", ""),
                           get(d, "mcp_path", ""),
                           Vector{String}(get(d, "mcp_args", String[])),
                           get(d, "projects_root", ""),
                           :unknown, now(UTC))
            s.workers[][wid] = w
        catch e
            @warn "skipping malformed worker entry" entry=d exception=e
        end
    end
end

# Like `save_workers!`: snapshot + write under `state.lock` (reentrant, so
# callers already holding it are unaffected). Without this, several savers ran
# unlocked — `sync_project_to_server!`, `rename_worker!`, `sync_across_workers!`,
# title backfill, etc. — iterating `values(s.projects[])` while locked writers
# mutated the dict, and two of them could share a temp file and rename a
# half-written projects.json into place (T2).
function save_projects!(s::ServerState)
    lock(s.lock) do
        data = [Dict("id" => p.id, "name" => p.name, "worker_id" => p.worker_id,
                     "server_path" => p.server_path, "worker_path" => p.worker_path,
                     "created" => string(p.created),
                     # `:syncing` is a runtime state — persist as `:stale` so a
                     # crash mid-sync doesn't leave the next start-up reporting
                     # "synced" for a half-transferred mirror.
                     "backup_status" => string(p.backup_status === :syncing ? :stale : p.backup_status),
                     "last_sync_at"  => p.last_sync_at === nothing ? nothing : string(p.last_sync_at),
                     "resume_session_id" => p.resume_session_id,
                     "auto_prompt"   => p.auto_prompt,
                     "title"         => p.title)
                for p in values(s.projects[])]
        atomic_write_json(projects_file(s), data)
    end
end

function load_projects!(s::ServerState)
    raw = load_json_tolerant(projects_file(s), "projects.json")
    raw === nothing && return
    for d in raw
        try
            # Migration: pre-UUID projects have only `worker_name` (a display
            # name string). Read either field; on the next worker connect the
            # value gets remapped to the worker's real UUID via
            # migrate_legacy_worker_refs! in worker_client.jl.
            wid = String(get(d, "worker_id", get(d, "worker_name", "")))
            p = ProjectInfo(d["id"], d["name"], wid,
                            d["server_path"], d["worker_path"],
                            DateTime(d["created"]))
            status_str = String(get(d, "backup_status", "unsynced"))
            p.backup_status = Symbol(status_str)
            last = get(d, "last_sync_at", nothing)
            p.last_sync_at = last === nothing ? nothing : DateTime(String(last))
            sid = get(d, "resume_session_id", nothing)
            p.resume_session_id = (sid === nothing || isempty(String(sid))) ?
                                       nothing : String(sid)
            ap = get(d, "auto_prompt", nothing)
            p.auto_prompt = (ap === nothing || isempty(String(ap))) ?
                                       nothing : String(ap)
            ti = get(d, "title", nothing)
            p.title = (ti === nothing || (ti isa AbstractString && isempty(ti))) ?
                                       nothing : String(ti)
            s.projects[][p.id] = p
        catch e
            @warn "skipping malformed project entry" entry=d exception=e
        end
    end
    dedup_projects!(s)
end

# Persist / restore the per-worker discovered-sessions cache. Best-effort:
# it's a cache (re-derivable by Rescan), so a corrupt file just starts empty.
function save_discovered!(s::ServerState)
    lock(s.lock) do
        # Snapshot under the lock so we don't serialise the dict while a
        # locked writer (`scan_and_store!`) is mutating it (T2).
        atomic_write_json(discovered_file(s), copy(s.discovered[]))
    end
end

function load_discovered!(s::ServerState)
    raw = load_json_tolerant(discovered_file(s), "discovered.json")
    raw === nothing && return
    d = Dict{String,Vector{Dict{String,Any}}}()
    for (wid, sessions) in raw
        sessions isa AbstractVector || continue
        d[String(wid)] = Dict{String,Any}[Dict{String,Any}(x) for x in sessions]
    end
    s.discovered[] = d
end

"""
    project_location_key(p) -> Tuple{String,String}

Identity tuple used to detect duplicate projects: a project is uniquely
identified by the worker it lives on (`worker_id`) and the absolute path
inside that worker (`worker_path`, normalised by stripping a trailing `/`).
"""
project_location_key(p::ProjectInfo) =
    (p.worker_id, rstrip(p.worker_path, '/'))

"""
    find_project_by_location(state, worker_id, worker_path)
        -> Union{ProjectInfo,Nothing}

Look up the existing project at `(worker_id, worker_path)`. The import
flows use this to short-circuit when the user re-imports the same folder
from the same worker — instead of generating a fresh `id` they reuse the
already-registered project.
"""
function find_project_by_location(state::ServerState,
                                   worker_id::AbstractString,
                                   worker_path::AbstractString)
    key = (String(worker_id), rstrip(String(worker_path), '/'))
    # Iterate under the lock (T14) — writers rehash `state.projects[]`.
    lock(state.lock) do
        for p in values(state.projects[])
            project_location_key(p) == key && return p
        end
        return nothing
    end
end

"""
    thread_dedup_key(p) -> Tuple{String,String,String}

A *thread's* identity: `(worker_id, worker_path, chat_id)`, where `chat_id`
is the claude session id (`resume_session_id`) or, for a brand-new thread
that hasn't a session yet, the project's own `id`. A folder
(`(worker_id, worker_path)`) can host several threads, so this is what we
de-duplicate on — NOT the folder key, which would wrongly merge sibling
threads of the same folder.
"""
thread_dedup_key(p::ProjectInfo) =
    (p.worker_id, rstrip(p.worker_path, '/'),
     something(p.resume_session_id, p.id))

"""
    thread_tag(p) -> String

A short human tag distinguishing sibling threads of the same folder: the
claude session id prefix for a resumed thread, or `new <id>` for a fresh one.
Used to disambiguate identical folder names in the active-chats sidebar.
"""
thread_tag(p::ProjectInfo) =
    p.resume_session_id === nothing ? "new " * first(p.id, 4) :
                                      first(p.resume_session_id, 8)

"""
    find_thread(state, worker_id, worker_path, chat_id) -> Union{ProjectInfo,Nothing}

Look up the thread `(worker_id, worker_path, chat_id)`, matching on the
claude session id (`resume_session_id`). `chat_id === nothing` means "a
brand-new thread" and never matches an existing one (so "+ New thread" and a
no-session import always create a fresh thread, while re-importing the same
session id reuses its thread and importing a *different* session of the same
folder creates a sibling).
"""
function find_thread(state::ServerState,
                     worker_id::AbstractString,
                     worker_path::AbstractString,
                     chat_id::Union{AbstractString,Nothing})
    chat_id === nothing && return nothing
    key = (String(worker_id), rstrip(String(worker_path), '/'), String(chat_id))
    # Iterate under the lock (T14) — writers rehash `state.projects[]`.
    lock(state.lock) do
        for p in values(state.projects[])
            (p.worker_id, rstrip(p.worker_path, '/'), p.resume_session_id) == key &&
                return p
        end
        return nothing
    end
end

"""
    compute_server_path(state, worker_name, name) -> String

Where the server keeps its mirror of `(worker_name, name)`'s files. We
disambiguate by worker name so two workers can each have a project called
"BonitoTeam" without their server-side mirrors (or `.bonitoTeam/chat.md`
histories) overwriting each other. The decision to *merge* same-named
projects from different workers is intentionally separate, and only
surfaces when the user explicitly asks to sync between them.
"""
compute_server_path(state::ServerState,
                     worker_name::AbstractString,
                     name::AbstractString) =
    joinpath(state.working_dir, "$(String(worker_name))-$(String(name))")

"""
    same_name_siblings(state, project_id) -> Vector{ProjectInfo}

Projects that share `project_id`'s display `name` but live on a *different*
worker. Because `compute_server_path` keeps each worker's mirror separate,
two workers can both carry a "BonitoTeam" project; these are the candidates
for an explicit cross-worker reconcile (see `sync_across_workers!`).
"""
function same_name_siblings(state::ServerState, project_id::AbstractString)
    haskey(state.projects[], project_id) || return ProjectInfo[]
    p = state.projects[][project_id]
    [q for q in values(state.projects[])
        if q.id != p.id && q.name == p.name && q.worker_id != p.worker_id]
end

# Collapse projects.json entries that are the SAME THREAD —
# `(worker_id, worker_path, chat_id)` (see `thread_dedup_key`). A folder can
# legitimately host several threads (different claude sessions, or new ones),
# so we de-dup per thread, NOT per folder: sibling threads of the same folder
# are kept. Genuine duplicates (e.g. the same session imported twice) share a
# `chat_id` and collapse to one. When picking which entry to keep we prefer
# the one carrying state we can't easily reconstruct (resume_session_id >
# auto_prompt > earliest `created`).
function dedup_projects!(s::ServerState)
    isempty(s.projects[]) && return
    groups = Dict{Tuple{String,String,String},Vector{ProjectInfo}}()
    for p in values(s.projects[])
        push!(get!(() -> ProjectInfo[], groups, thread_dedup_key(p)), p)
    end
    dropped = Tuple{String,String,String}[]   # (worker, path, dropped_id)
    for (key, members) in groups
        length(members) <= 1 && continue
        keeper = pick_dedup_keeper(members)
        for p in members
            p === keeper && continue
            delete!(s.projects[], p.id)
            push!(dropped, (key[1], key[2], p.id))
        end
    end
    if !isempty(dropped)
        @warn "dedup: collapsed duplicate threads sharing (worker_id, worker_path, chat_id)" dropped
        save_projects!(s)
    end
    return
end

function pick_dedup_keeper(members::Vector{ProjectInfo})
    # 1. resume_session_id set → keep that (otherwise we'd silently drop the
    #    `session/load` link to the imported claude session).
    for p in members
        p.resume_session_id !== nothing && return p
    end
    # 2. auto_prompt set → keep that (the seeded "fix this PR" prompt is
    #    user-visible state we can't reconstruct).
    for p in members
        p.auto_prompt !== nothing && return p
    end
    # 3. else: keep the earliest-created (the one the user has presumably
    #    been using longer).
    return reduce((a, b) -> a.created <= b.created ? a : b, members)
end
