# Single source of truth for server-side state. Replaces 14 module-level
# globals (WORKERS, PROJECTS, PENDING_*, STATE_VERSION, etc.) with one
# `ServerState` struct constructed in `serve()` and threaded through every
# route handler / dashboard / chat closure.
#
# Why one struct: each `serve()` call is one server. Module globals made
# multi-instance testing impossible and let stale observables from a
# re-rendered form leak into a new render through the shared dict.

mutable struct WorkerInfo
    # Stable per-install identity (UUID generated by the worker on first run
    # and persisted to ~/.local/share/bonitoteam-worker/worker_id). This is
    # the dict key in `ServerState.workers` so a worker survives hostname /
    # IP / display-name changes — moving a laptop between Wi-Fi networks,
    # or two installs that both default to "localhost", no longer collide.
    worker_id::String
    name::String                       # display name (mutable; user-renameable)
    url::String                        # ws://host:port
    secret::String
    ssh_target::Union{String,Nothing}  # for ssh-based rsync: "user@host". nothing → local rsync
    # discovered via probe
    hostname::String
    home::String
    mcp_path::String                   # MCP launch command on worker (the julia binary)
    mcp_args::Vector{String}           # MCP launch args on worker (--project=…, -e …)
    projects_root::String              # rsync destination root on worker
    # runtime
    status::Symbol                     # :unknown, :online, :offline
    last_check::DateTime
end

mutable struct ProjectInfo
    id::String                         # short uuid
    name::String                       # display name + dir name (server + worker)
    # FK into `ServerState.workers` — stores the worker's stable UUID, NOT
    # its (mutable) display name. Old projects.json entries that still carry
    # a display name string in the `worker_name` field get migrated lazily
    # on the next worker connect (see handle_worker_control).
    worker_id::String
    server_path::String                # canonical copy on server (= state.working_dir/name)
    worker_path::String                # mirrored copy on worker (= worker.projects_root/name)
    created::DateTime
    # At most one active ACP session per project. Acquired when
    # ensure_project_session! brings up the ChatModel; released automatically
    # when the bound worker's control WS drops (the claude process is gone
    # with it). Worker-only-write model means there's no checksum/divergence
    # state — anything claude writes on the worker auto-flows back to the
    # server, the operator never edits server_path.
    locked_by::Union{String,Nothing}      # worker_name when active, else nothing
    locked_at::Union{DateTime,Nothing}
    # :unsynced (default for worker-imported projects) — server has no copy.
    # :syncing — a librsync transfer is in progress.
    # :synced — last librsync transfer completed successfully; server has a copy.
    # :stale — was synced once but content has likely diverged since.
    # Persistence: only :unsynced vs :synced is durable; :syncing always resets
    # to :stale on restart so a crash mid-sync doesn't leave a wrong "synced".
    backup_status::Symbol
    last_sync_at::Union{DateTime,Nothing}
    # Set when the project was imported from an existing claude-agent-acp
    # session — the .jsonl basename in ~/.claude/projects/<encoded>/ on the
    # worker. start_session(::WorkerTransport) uses session/load with this ID to bring
    # the conversation history back to where claude left off; nothing → fresh
    # session/new. Persisted so server restarts still resume.
    resume_session_id::Union{String,Nothing}
    # If set, the chat fires this prompt as the first user message the next
    # time it brings up an ACP session — used by the "From GitHub" template
    # to seed "fix this issue" / "review this PR" without the operator having
    # to retype it. Cleared (and persisted as nothing) once the prompt has
    # been delivered, so a session restart doesn't re-fire.
    auto_prompt::Union{String,Nothing}
end

ProjectInfo(id, name, worker_id, server_path, worker_path, created) =
    ProjectInfo(id, name, worker_id, server_path, worker_path, created,
                nothing, nothing, :unsynced, nothing, nothing, nothing)

"""
    ServerState

Everything one running BonitoTeam server needs. Constructed in `serve()`
and captured by route closures, dashboard / chat apps, and worker control
handlers. Five things deserve a paragraph each:

- `pending_rpcs` collapses what used to be five separate dicts (one per
  RPC type). The keys are uuids, so cross-RPC-type collisions can't happen,
  and the unified shape removes a lot of duplicated bookkeeping.
- `workers` and `projects` are themselves Observables wrapping the live
  Dicts. Mutators do in-place updates and then `notify(state.projects)`
  (or `state.workers`) to fan out to listeners. Sidebar / dashboard
  consumers `map(state.projects) do projects … end` — they get the
  current Dict by value, so adding a worker doesn't redraw the project
  list and vice versa. There's no separate version-int sentinel: the
  data IS the change signal.
- `worker_control_ws` keys workers by name (the same key as `workers`).
- `srv` is filled in after `Bonito.Server` is constructed (chicken-and-egg:
  the dashboard app captures the state, but the server constructor takes
  the dashboard).
- `worker_secret` is the auth token every worker presents on its hello
  frame; same secret across all workers, baked into the install script.
"""
mutable struct ServerState
    # Convention: every shared-state struct's first field is its lock.
    # Bonito App bodies run on different threads per browser tab and the
    # WS handler / RPC pumps can mutate the dicts at any time, so all
    # multi-field reads/writes go through `lock(state.lock) do … end`.
    # Per-session views are produced by `Base.copy(state, session)` (below)
    # which SHARES this lock with the parent — sessions cooperate, they
    # don't each get their own mutex. See .claude/skills/bonito/SKILL.md
    # § "Thread-safe shared state".
    lock :: ReentrantLock

    # Disk paths (immutable after construction)
    state_dir   :: String
    working_dir :: String
    # Auth
    worker_secret :: String
    # Live Bonito server (set by serve() after construction)
    srv :: Union{Bonito.Server,Nothing}

    # Persisted state, wrapped in Observables so consumers can `map` them
    # directly (no sentinel version-int). Mutators do in-place updates and
    # then `notify(state.workers)` / `notify(state.projects)` to fan out
    # to listeners. The .{} access forms — `state.projects[][id]`,
    # `values(state.projects[])`, etc. — are the price for collection-
    # level reactivity, but they're mechanical and the win is that the
    # sidebar (project-only) ignores worker churn and the worker cards
    # ignore project churn.
    #
    # SHARED parents: App bodies must not `map(state.projects)` directly.
    # Take `view = copy(state, session)` and `map(view.projects)` so each
    # session subscribes to its own connected child Observable (auto-GC'd
    # on session close).
    workers  :: Observable{Dict{String,WorkerInfo}}
    projects :: Observable{Dict{String,ProjectInfo}}

    # Runtime caches (not persisted). One ChatModel per project, lazily built
    # the first time the project's chat is opened or the worker reconnects;
    # holds the live ACP client and message store. The unified app's main
    # panel pulls the model from here when a project icon is selected.
    chat_models :: Dict{String,Any}   # id → ChatModel

    # Live worker connections (name → HTTP.WebSocket)
    worker_control_ws :: Dict{String,Any}

    # Pending request_id → channel handoffs for every RPC type. Channel{Any}
    # because the answer shape varies (WS for handoff, Dict for rpc result).
    pending_rpcs :: Dict{String,Channel{Any}}
end

"""
    ServerState(; state_dir, working_dir, worker_secret) → ServerState

Construct a fresh state, loading workers + projects from `state_dir`
(`workers.json`, `projects.json`). `working_dir` is created if missing.
"""
function ServerState(; state_dir::String,
                       working_dir::String,
                       worker_secret::String)
    mkpath(working_dir)
    s = ServerState(
        ReentrantLock(),
        state_dir, working_dir, worker_secret,
        nothing,
        Observable(Dict{String,WorkerInfo}()),    # workers
        Observable(Dict{String,ProjectInfo}()),   # projects
        Dict{String,Any}(),                       # chat_models
        Dict{String,Any}(),                       # worker_control_ws
        Dict{String,Channel{Any}}(),              # pending_rpcs
    )
    load_workers!(s)
    load_projects!(s)
    return s
end

# Per-session view of `state`. SHARES the lock, dicts, and the live `srv`
# field with the parent — sessions cooperate on the same workers/projects/
# chat_models tables and the same lock. Each Observable field is bridged
# via `map(identity, session, obs)`: that produces a connected child
# AND registers the parent→child callback on `session.deregister_callbacks`,
# so when the tab closes the bridge tears down automatically. (Plain
# `copy(obs)` would leak the callback on the parent forever.)
#
# Use `view = copy(state, session)` at the top of every `App() do session ... end` body.
function Base.copy(s::ServerState, session::Bonito.Session)
    lock(s.lock) do
        ServerState(
            s.lock,
            s.state_dir, s.working_dir, s.worker_secret,
            s.srv,
            map(identity, session, s.workers),
            map(identity, session, s.projects),
            s.chat_models,
            s.worker_control_ws,
            s.pending_rpcs,
        )
    end
end

workers_file(s::ServerState)  = joinpath(s.state_dir, "workers.json")
projects_file(s::ServerState) = joinpath(s.state_dir, "projects.json")

# Setting an Observable propagates to the browser via Bonito's WebSocket;
# if a session is broken (e.g. a stale tab whose hashed asset URLs went 404
# after a redeploy), Bonito surfaces that as a JSException from the
# observable update. We don't want a stale UI tab to break server-side
# operations, so we swallow + log via these helpers instead of letting the
# JSException unwind a server thread.

# Best-effort `obs[] = val`. Use for plain Observable updates.
function safe_set!(obs::Observable, val)
    try
        obs[] = val
    catch e
        @debug "safe_set!: observable propagation failed (likely stale browser session)" exception=e
    end
    return nothing
end

# Best-effort `notify(obs)` — fires listeners without changing the value.
# Use after in-place mutation of `state.workers[]` / `state.projects[]`.
function safe_notify!(obs::Observable)
    try
        notify(obs)
    catch e
        @debug "safe_notify!: observable propagation failed (likely stale browser session)" exception=e
    end
    return nothing
end

# ── Persistence ───────────────────────────────────────────────────────────
# Atomic JSON write: serialise to a sibling .tmp first, then rename into place.
# `rename(2)` on the same filesystem is atomic, so a crash mid-save can leave
# only the old file or only the new — never a half-written file.
function atomic_write_json(path::String, data)
    mkpath(dirname(path))
    tmp = path * ".tmp"
    open(tmp, "w") do io
        JSON.print(io, data, 2)
    end
    mv(tmp, path; force = true)
end

# Read JSON with corruption tolerance: if the file is truncated/garbled (e.g.
# from a crash before atomic_write_json existed, or a manual edit gone wrong),
# log a warning, move it aside as `<file>.bad`, and continue with empty state.
# We'd rather lose worker/project metadata than refuse to start the server.
function load_json_tolerant(path::String, label::String)
    isfile(path) || return nothing
    try
        return JSON.parsefile(path)
    catch e
        bad = path * ".bad-" * Dates.format(now(UTC), "yyyymmddTHHMMSS")
        try mv(path, bad; force = true) catch end
        @warn "$label: failed to parse — moved aside, starting empty" path bad exception=e
        return nothing
    end
end

function save_workers!(s::ServerState)
    data = [Dict("worker_id" => w.worker_id,
                 "name" => w.name, "url" => w.url, "secret" => w.secret,
                 "ssh_target" => w.ssh_target,
                 "hostname" => w.hostname, "home" => w.home,
                 "mcp_path" => w.mcp_path, "mcp_args" => w.mcp_args,
                 "projects_root" => w.projects_root)
            for w in values(s.workers[])]
    atomic_write_json(workers_file(s), data)
end

function load_workers!(s::ServerState)
    raw = load_json_tolerant(workers_file(s), "workers.json")
    raw === nothing && return
    for d in raw
        try
            # Migration: workers.json from before the worker_id field was
            # introduced has only `name`. Use the legacy display name as
            # a stand-in worker_id so existing project FKs keep resolving;
            # the next worker reconnect will overwrite this with the real
            # UUID from the worker's hello frame.
            wid = String(get(d, "worker_id", d["name"]))
            w = WorkerInfo(wid, d["name"], d["url"], d["secret"],
                           get(d, "ssh_target", nothing),
                           get(d, "hostname", ""), get(d, "home", ""),
                           get(d, "mcp_path", ""),
                           Vector{String}(get(d, "mcp_args", String[])),
                           get(d, "projects_root", ""),
                           :unknown, now(UTC))
            s.workers[][wid] = w
        catch e
            @warn "skipping malformed worker entry" entry=d exception=e
        end
    end
end

function save_projects!(s::ServerState)
    data = [Dict("id" => p.id, "name" => p.name, "worker_id" => p.worker_id,
                 "server_path" => p.server_path, "worker_path" => p.worker_path,
                 "created" => string(p.created),
                 # `:syncing` is a runtime state — persist as `:stale` so a
                 # crash mid-sync doesn't leave the next start-up reporting
                 # "synced" for a half-transferred mirror.
                 "backup_status" => string(p.backup_status === :syncing ? :stale : p.backup_status),
                 "last_sync_at"  => p.last_sync_at === nothing ? nothing : string(p.last_sync_at),
                 "resume_session_id" => p.resume_session_id,
                 "auto_prompt"   => p.auto_prompt)
            for p in values(s.projects[])]
    atomic_write_json(projects_file(s), data)
end

function load_projects!(s::ServerState)
    raw = load_json_tolerant(projects_file(s), "projects.json")
    raw === nothing && return
    for d in raw
        try
            # Migration: pre-UUID projects have only `worker_name` (a display
            # name string). Read either field; on the next worker connect the
            # value gets remapped to the worker's real UUID via
            # migrate_legacy_worker_refs! in worker_client.jl.
            wid = String(get(d, "worker_id", get(d, "worker_name", "")))
            p = ProjectInfo(d["id"], d["name"], wid,
                            d["server_path"], d["worker_path"],
                            DateTime(d["created"]))
            status_str = String(get(d, "backup_status", "unsynced"))
            p.backup_status = Symbol(status_str)
            last = get(d, "last_sync_at", nothing)
            p.last_sync_at = last === nothing ? nothing : DateTime(String(last))
            sid = get(d, "resume_session_id", nothing)
            p.resume_session_id = (sid === nothing || isempty(String(sid))) ?
                                       nothing : String(sid)
            ap = get(d, "auto_prompt", nothing)
            p.auto_prompt = (ap === nothing || isempty(String(ap))) ?
                                       nothing : String(ap)
            s.projects[][p.id] = p
        catch e
            @warn "skipping malformed project entry" entry=d exception=e
        end
    end
    dedup_projects!(s)
end

"""
    project_location_key(p) -> Tuple{String,String}

Identity tuple used to detect duplicate projects: a project is uniquely
identified by the worker it lives on (`worker_id`) and the absolute path
inside that worker (`worker_path`, normalised by stripping a trailing `/`).
"""
project_location_key(p::ProjectInfo) =
    (p.worker_id, rstrip(p.worker_path, '/'))

"""
    find_project_by_location(state, worker_id, worker_path)
        -> Union{ProjectInfo,Nothing}

Look up the existing project at `(worker_id, worker_path)`. The import
flows use this to short-circuit when the user re-imports the same folder
from the same worker — instead of generating a fresh `id` they reuse the
already-registered project.
"""
function find_project_by_location(state::ServerState,
                                   worker_id::AbstractString,
                                   worker_path::AbstractString)
    key = (String(worker_id), rstrip(String(worker_path), '/'))
    for p in values(state.projects[])
        project_location_key(p) == key && return p
    end
    return nothing
end

"""
    find_project_by_name(state, name) -> Union{ProjectInfo,Nothing}

Look up a project by its display/dir name. Used by the import-collision
flow: two projects with the same `name` would land at the same
`server_path` (`<working_dir>/<name>`), so the second import has to
either reassign the existing one to the new worker, keep it, or be
imported under a different name.
"""
function find_project_by_name(state::ServerState, name::AbstractString)
    target = String(name)
    for p in values(state.projects[])
        p.name == target && return p
    end
    return nothing
end

# Collapse projects.json entries that share `(worker_id, worker_path)`.
# Same coordinates means the same on-disk folder — and since the project
# name is derived from `basename(worker_path)`, both copies actually share
# the same `server_path` (and therefore the same `.bonitoTeam/chat.md`),
# so dropping the runner-up loses no chat history. When picking which
# entry to keep we prefer the one carrying state we can't easily
# reconstruct (resume_session_id > auto_prompt > earliest `created`).
function dedup_projects!(s::ServerState)
    isempty(s.projects[]) && return
    groups = Dict{Tuple{String,String},Vector{ProjectInfo}}()
    for p in values(s.projects[])
        push!(get!(() -> ProjectInfo[], groups, project_location_key(p)), p)
    end
    dropped = Tuple{String,String,String}[]   # (worker, path, dropped_id)
    for (key, members) in groups
        length(members) <= 1 && continue
        keeper = pick_dedup_keeper(members)
        for p in members
            p === keeper && continue
            delete!(s.projects[], p.id)
            push!(dropped, (key[1], key[2], p.id))
        end
    end
    if !isempty(dropped)
        @warn "dedup: collapsed duplicate projects sharing (worker_id, worker_path)" dropped
        save_projects!(s)
    end
    return
end

function pick_dedup_keeper(members::Vector{ProjectInfo})
    # 1. resume_session_id set → keep that (otherwise we'd silently drop the
    #    `session/load` link to the imported claude session).
    for p in members
        p.resume_session_id !== nothing && return p
    end
    # 2. auto_prompt set → keep that (the seeded "fix this PR" prompt is
    #    user-visible state we can't reconstruct).
    for p in members
        p.auto_prompt !== nothing && return p
    end
    # 3. else: keep the earliest-created (the one the user has presumably
    #    been using longer).
    return reduce((a, b) -> a.created <= b.created ? a : b, members)
end
