const ChatStyles = Bonito.Styles(
    # ── Tokens (shared with the dashboard) ────────────────────────────────────
    CSS(":root",
        "--bt-bg"            => "#fafaf9",
        "--bt-surface"       => "#ffffff",
        "--bt-surface-2"     => "#f8fafc",
        "--bt-border"        => "rgba(15,23,42,0.08)",
        "--bt-border-strong" => "rgba(15,23,42,0.14)",
        "--bt-text"          => "#0f172a",
        "--bt-text-muted"    => "#64748b",
        "--bt-text-faint"    => "#94a3b8",
        "--bt-accent"        => "#3b82f6",
        "--bt-accent-hover"  => "#2563eb",
        "--bt-success"       => "#10b981",
        "--bt-error"         => "#ef4444",
        "--bt-warning"       => "#f59e0b",
        "--bt-shadow-sm"     => "0 1px 2px rgba(15,23,42,0.05)",
        "--bt-shadow-md"     => "0 4px 12px rgba(15,23,42,0.08)",
        "--bt-radius"        => "8px",
        "--bt-radius-sm"     => "6px"),

    # ── Reset ────────────────────────────────────────────────────────────────
    CSS("html, body",
        "height" => "100%", "margin" => "0", "padding" => "0",
        "overflow" => "hidden"),

    # ── App shell — full-viewport flex column ────────────────────────────────
    CSS(".bt-app",
        "display" => "flex", "flex-direction" => "column",
        "height" => "100svh",
        "font-family" => "'Inter', system-ui, -apple-system, sans-serif",
        "font-size" => "14px",
        "background" => "var(--bt-bg)",
        "color" => "var(--bt-text)",
        "box-sizing" => "border-box",
        "overscroll-behavior" => "none",
        "-webkit-font-smoothing" => "antialiased"),

    # ── Header ───────────────────────────────────────────────────────────────
    # Outer spans full width (border-bottom looks correct); inner row caps at
    # the same content width as messages/input on desktop.
    CSS(".bt-header",
        "display" => "flex", "justify-content" => "center",
        "padding" => "10px 16px",
        "background" => "var(--bt-surface)",
        "border-bottom" => "1px solid var(--bt-border)",
        "flex-shrink" => "0",
        "min-height" => "44px",
        "box-sizing" => "border-box"),
    CSS(".bt-header-row",
        "display" => "flex", "align-items" => "center", "gap" => "10px",
        "width" => "100%", "max-width" => "880px"),
    CSS(".bt-header-back",
        "color" => "var(--bt-text-muted)", "text-decoration" => "none",
        "font-size" => "16px",
        "padding" => "4px 8px", "border-radius" => "4px",
        "transition" => "background 80ms, color 80ms",
        "flex-shrink" => "0"),
    CSS(".bt-header-back:hover",
        "background" => "var(--bt-surface-2)",
        "color" => "var(--bt-text)"),
    CSS(".bt-header-title",
        "font-weight" => "600", "font-size" => "14px",
        "min-width" => "0", "overflow" => "hidden",
        "text-overflow" => "ellipsis", "white-space" => "nowrap",
        "flex" => "1 1 auto"),
    CSS(".bt-header-cwd",
        "font-family" => "ui-monospace, monospace", "font-size" => "12px",
        "color" => "var(--bt-text-muted)", "font-weight" => "400",
        "margin-left" => "6px"),

    # ── Status dot (online/offline/streaming) ────────────────────────────────
    CSS(".bt-dot",
        "display" => "inline-block",
        "width" => "8px", "height" => "8px",
        "border-radius" => "50%", "flex-shrink" => "0"),
    CSS(".bt-dot-online",
        "background" => "var(--bt-success)",
        "box-shadow" => "0 0 0 3px rgba(16,185,129,0.18)"),
    CSS(".bt-dot-offline", "background" => "var(--bt-text-faint)"),

    # ── Session-ended banner ─────────────────────────────────────────────────
    # Shown when the ACP connection drops mid-conversation. Mirrors the
    # bt-error style but adds a Restart action; sits between header and
    # message scroll so it's always visible.
    CSS(".bt-banner-error",
        "background" => "#fef2f2", "color" => "#b91c1c",
        "border" => "1px solid #fecaca",
        "border-radius" => "var(--bt-radius)",
        "padding" => "10px 14px",
        "margin" => "12px 16px 0",
        "display" => "flex", "align-items" => "center", "gap" => "12px",
        "font-size" => "13px"),
    CSS(".bt-banner-error .bt-btn",
        "flex-shrink" => "0"),
    CSS(".bt-banner-detail",
        "color" => "#7f1d1d", "font-size" => "12px",
        "margin-top" => "2px",
        "font-family" => "ui-monospace, monospace",
        "white-space" => "nowrap", "overflow" => "hidden",
        "text-overflow" => "ellipsis"),
    CSS(".bt-btn-secondary",
        "background" => "var(--bt-surface)", "color" => "var(--bt-text)",
        "border" => "1px solid var(--bt-border-strong)",
        "padding" => "6px 12px", "border-radius" => "var(--bt-radius-sm)",
        "font-size" => "13px", "cursor" => "pointer"),
    CSS(".bt-btn-secondary:hover",
        "background" => "var(--bt-surface-2)"),

    # ── Messages container ───────────────────────────────────────────────────
    # On wide screens the column self-centers (max-width + align-self), so
    # bubbles don't sprawl across a 1440px+ viewport. Scrollbar stays at the
    # right edge of the column rather than the screen edge — natural for a
    # chat app with content margins.
    CSS(".bt-messages",
        "flex" => "1 1 0", "min-height" => "0",
        "overflow-y" => "auto", "overflow-x" => "hidden",
        "-webkit-overflow-scrolling" => "touch",
        "overscroll-behavior-y" => "contain",
        "overflow-anchor" => "auto",
        "padding" => "16px",
        "display" => "flex", "flex-direction" => "column",
        "gap" => "10px",
        "width" => "100%", "max-width" => "880px",
        "align-self" => "center",
        "box-sizing" => "border-box"),
    CSS(".bt-spacer-top, .bt-spacer-bottom",
        "flex-shrink" => "0", "overflow-anchor" => "none"),

    # ── User message ─────────────────────────────────────────────────────────
    # max-width caps the bubble at a comfortable reading width on wide screens
    CSS(".bt-user-msg",
        "align-self" => "flex-end",
        "max-width" => "min(80%, 640px)",
        "background" => "var(--bt-accent)", "color" => "#fff",
        "border-radius" => "12px 12px 2px 12px",
        "padding" => "10px 14px",
        "font-size" => "14px", "line-height" => "1.5",
        "white-space" => "pre-wrap", "word-break" => "break-word",
        "box-shadow" => "var(--bt-shadow-sm)"),

    # ── Agent message ────────────────────────────────────────────────────────
    CSS(".bt-agent-msg",
        "align-self" => "flex-start",
        "max-width" => "min(85%, 760px)",
        "background" => "var(--bt-surface)",
        "border" => "1px solid var(--bt-border)",
        "border-radius" => "2px 12px 12px 12px",
        "padding" => "10px 14px",
        "font-size" => "14px", "line-height" => "1.55",
        "word-break" => "break-word",
        "box-shadow" => "var(--bt-shadow-sm)"),

    # Streaming cursor blink
    CSS(".bt-stream-text::after",
        "content" => "\"▋\"",
        "animation" => "bt-cursor 0.8s step-end infinite",
        "color" => "var(--bt-accent)",
        "margin-left" => "1px"),
    CSS("@keyframes bt-cursor",
        CSS("0%, 100%", "opacity" => "1"),
        CSS("50%", "opacity" => "0")),

    # ── Thought (extended thinking) ──────────────────────────────────────────
    CSS(".bt-thought-msg",
        "align-self" => "flex-start",
        "max-width" => "min(85%, 760px)",
        "border" => "1px dashed var(--bt-border-strong)",
        "border-radius" => "10px",
        "background" => "transparent",
        "color" => "var(--bt-text-muted)"),
    CSS(".bt-thought-details", "padding" => "0"),
    CSS(".bt-thought-summary",
        "padding" => "8px 12px",
        "cursor" => "pointer",
        "user-select" => "none",
        "list-style" => "none",
        "font-size" => "13px",
        "display" => "flex", "align-items" => "center", "gap" => "6px"),
    CSS(".bt-thought-summary::-webkit-details-marker", "display" => "none"),
    CSS(".bt-thought-summary::before",
        "content" => "\"▸\"",
        "color" => "var(--bt-text-faint)",
        "transition" => "transform 120ms"),
    CSS("details[open] > .bt-thought-summary::before",
        "transform" => "rotate(90deg)"),
    CSS(".bt-thought-body",
        "padding" => "0 12px 10px 28px",
        "white-space" => "pre-wrap", "word-break" => "break-word",
        "font-size" => "12.5px", "line-height" => "1.5",
        "color" => "var(--bt-text-muted)"),

    # ── Tool call card ───────────────────────────────────────────────────────
    CSS(".bt-tool-msg",
        "align-self" => "flex-start",
        "max-width" => "min(92%, 800px)",
        "background" => "var(--bt-surface)",
        "border" => "1px solid var(--bt-border)",
        "border-radius" => "var(--bt-radius-sm)",
        "font-size" => "13px",
        "box-shadow" => "var(--bt-shadow-sm)",
        "overflow" => "hidden"),
    CSS(".bt-tool-header",
        "display" => "flex", "align-items" => "center", "gap" => "8px",
        "padding" => "8px 12px",
        "cursor" => "pointer",
        "user-select" => "none",
        "transition" => "background 80ms"),
    CSS(".bt-tool-header:hover",
        "background" => "var(--bt-surface-2)"),
    CSS(".bt-tool-toggle",
        "color" => "var(--bt-text-faint)", "font-size" => "11px",
        "transition" => "transform 120ms",
        "flex-shrink" => "0",
        "width" => "10px"),
    CSS(".bt-tool-header[data-expanded=\"true\"] .bt-tool-toggle",
        "transform" => "rotate(90deg)"),
    CSS(".bt-tool-kind",
        "font-size" => "13px", "flex-shrink" => "0"),
    CSS(".bt-tool-title",
        "flex" => "1 1 auto", "min-width" => "0",
        "font-family" => "ui-monospace, monospace", "font-size" => "12px",
        "overflow" => "hidden", "text-overflow" => "ellipsis",
        "white-space" => "nowrap"),
    CSS(".bt-tool-summary",
        "color" => "var(--bt-text-muted)", "font-size" => "11.5px",
        "flex-shrink" => "0",
        "white-space" => "nowrap"),

    # Tool status — slim pill, harmonized with dashboard
    CSS(".bt-tool-status",
        "display" => "inline-flex", "align-items" => "center",
        "gap" => "4px",
        "font-size" => "11px", "font-weight" => "500",
        "padding" => "1px 8px",
        "border-radius" => "999px",
        "white-space" => "nowrap", "flex-shrink" => "0"),
    CSS(".bt-status-pending",
        "background" => "rgba(245,158,11,0.12)", "color" => "#92400e"),
    CSS(".bt-status-in_progress",
        "background" => "rgba(59,130,246,0.12)", "color" => "#1d4ed8"),
    CSS(".bt-status-completed",
        "background" => "rgba(16,185,129,0.12)", "color" => "#047857"),
    CSS(".bt-status-failed",
        "background" => "rgba(239,68,68,0.12)", "color" => "#b91c1c"),

    CSS(".bt-tool-body",
        "padding" => "0 12px 10px",
        "border-top" => "1px solid var(--bt-border)"),
    CSS(".bt-tool-empty",
        "padding" => "8px 0",
        "color" => "var(--bt-text-faint)",
        "font-style" => "italic", "font-size" => "12px"),
    CSS(".bt-tool-md",
        "font-size" => "13px", "line-height" => "1.5",
        "padding-top" => "8px"),

    # ── Plan ─────────────────────────────────────────────────────────────────
    CSS(".bt-plan-msg",
        "align-self" => "flex-start",
        "max-width" => "min(88%, 760px)",
        "border" => "1px solid var(--bt-border)",
        "border-radius" => "var(--bt-radius-sm)",
        "background" => "var(--bt-surface)",
        "padding" => "10px 14px",
        "font-size" => "13px",
        "box-shadow" => "var(--bt-shadow-sm)"),
    CSS(".bt-plan-entry",
        "display" => "flex", "align-items" => "flex-start",
        "gap" => "8px", "padding" => "3px 0",
        "color" => "var(--bt-text)"),
    CSS(".bt-plan-status",
        "width" => "16px", "flex-shrink" => "0",
        "text-align" => "center",
        "color" => "var(--bt-text-muted)",
        "font-weight" => "600"),

    # ── Markdown inside agent bubble ─────────────────────────────────────────
    CSS(".bt-agent-msg .markdown-body, .bt-agent-msg .markdown",
        "background" => "none", "border" => "none", "padding" => "0",
        "font-size" => "inherit", "font-family" => "inherit",
        "color" => "inherit", "line-height" => "1.55"),
    CSS(".bt-agent-msg .markdown-body > *:first-child, .bt-agent-msg .markdown > *:first-child",
        "margin-top" => "0"),
    CSS(".bt-agent-msg .markdown-body > *:last-child, .bt-agent-msg .markdown > *:last-child",
        "margin-bottom" => "0"),
    CSS(".bt-agent-msg pre",
        "background" => "#0f172a", "color" => "#e2e8f0",
        "border-radius" => "var(--bt-radius-sm)",
        "padding" => "10px 14px",
        "overflow-x" => "auto",
        "font-size" => "12px", "line-height" => "1.5",
        "margin" => "8px 0"),
    CSS(".bt-agent-msg code",
        "background" => "rgba(15,23,42,0.06)",
        "border-radius" => "3px",
        "padding" => "1px 5px",
        "font-size" => "12.5px",
        "font-family" => "ui-monospace, monospace"),
    CSS(".bt-agent-msg pre code",
        "background" => "none", "padding" => "0",
        "color" => "inherit"),

    # ── Busy indicator ───────────────────────────────────────────────────────
    CSS(".bt-busy",
        "flex-shrink" => "0", "height" => "0", "overflow" => "hidden",
        "display" => "flex", "gap" => "4px", "align-items" => "center",
        "padding" => "0 16px",
        "transition" => "height 150ms ease, padding 150ms ease"),
    CSS(".bt-busy.bt-busy-active",
        "height" => "28px", "padding" => "4px 16px"),
    CSS(".bt-busy-dot",
        "width" => "7px", "height" => "7px", "border-radius" => "50%",
        "background" => "var(--bt-accent)",
        "animation" => "bt-pulse 1.2s ease-in-out infinite"),
    CSS(".bt-busy-dot:nth-child(2)", "animation-delay" => "0.2s"),
    CSS(".bt-busy-dot:nth-child(3)", "animation-delay" => "0.4s"),
    CSS("@keyframes bt-pulse",
        CSS("0%, 100%", "opacity" => "0.3", "transform" => "scale(0.8)"),
        CSS("50%",      "opacity" => "1",   "transform" => "scale(1.2)")),

    # ── Input area ───────────────────────────────────────────────────────────
    # Outer area spans full width (so the top border + background look right);
    # inner row is centered with the same max-width as the messages column.
    CSS(".bt-input-area",
        "flex-shrink" => "0",
        "border-top" => "1px solid var(--bt-border)",
        "padding" => "12px 14px",
        "padding-bottom" => "max(12px, env(safe-area-inset-bottom))",
        "display" => "flex", "justify-content" => "center",
        "background" => "var(--bt-surface)"),
    CSS(".bt-input-row",
        "display" => "flex", "gap" => "8px", "align-items" => "flex-end",
        "width" => "100%", "max-width" => "880px"),
    CSS(".bt-text-input",
        "flex" => "1 1 auto", "min-width" => "0",
        "border" => "1px solid var(--bt-border-strong)",
        "border-radius" => "20px",
        "padding" => "10px 14px",
        "font-size" => "16px",                          # iOS no-zoom threshold
        "min-height" => "40px", "max-height" => "120px",
        "font-family" => "inherit",
        "color" => "var(--bt-text)",
        "background" => "var(--bt-bg)",
        "outline" => "none", "box-sizing" => "border-box",
        "resize" => "none", "overflow-y" => "auto",
        "line-height" => "1.4",
        "transition" => "border-color 120ms, box-shadow 120ms"),
    CSS(".bt-text-input::placeholder",
        "color" => "var(--bt-text-faint)"),
    CSS(".bt-text-input:focus",
        "border-color" => "var(--bt-accent)",
        "box-shadow" => "0 0 0 3px rgba(59,130,246,0.18)"),
    # Thin, modern scrollbar instead of the Linux/Electron default with up/down
    # arrow buttons. Only visible when textarea grows past max-height.
    CSS(".bt-text-input",
        "scrollbar-width" => "thin",
        "scrollbar-color" => "var(--bt-border-strong) transparent"),
    CSS(".bt-text-input::-webkit-scrollbar",
        "width" => "6px"),
    CSS(".bt-text-input::-webkit-scrollbar-thumb",
        "background" => "var(--bt-border-strong)",
        "border-radius" => "3px"),
    CSS(".bt-text-input::-webkit-scrollbar-button",
        "display" => "none"),

    # Send / stop buttons — circles, big enough for thumb
    CSS(".bt-send-btn, .bt-stop-btn",
        "border" => "none", "border-radius" => "50%",
        "width" => "40px", "height" => "40px",
        "font-size" => "20px",                       # larger glyph fills the circle
        "line-height" => "1",
        "cursor" => "pointer", "flex-shrink" => "0",
        "display" => "flex", "align-items" => "center",
        "justify-content" => "center", "padding" => "0",
        "transition" => "background 120ms, transform 80ms, opacity 120ms"),
    CSS(".bt-send-btn",
        "background" => "var(--bt-accent)", "color" => "#fff"),
    CSS(".bt-send-btn:hover",  "background" => "var(--bt-accent-hover)"),
    CSS(".bt-send-btn:active", "transform" => "scale(0.95)"),
    CSS(".bt-send-btn:disabled",
        "opacity" => "0.4", "cursor" => "not-allowed"),
    CSS(".bt-stop-btn",
        "background" => "var(--bt-surface)",
        "color" => "var(--bt-error)",
        "border" => "1px solid var(--bt-border-strong)"),
    CSS(".bt-stop-btn:hover",
        "background" => "rgba(239,68,68,0.08)",
        "border-color" => "var(--bt-error)"),

    # ── Responsive ───────────────────────────────────────────────────────────
    CSS("@media (max-width: 480px)",
        # Tighter padding on very small screens
        CSS(".bt-messages", "padding" => "12px"),
        CSS(".bt-input-area", "padding" => "10px 12px",
            "padding-bottom" => "max(10px, env(safe-area-inset-bottom))"),
        # Slightly tighter bubbles
        CSS(".bt-user-msg, .bt-agent-msg", "max-width" => "88%"),
        CSS(".bt-tool-msg",                "max-width" => "100%"),
        CSS(".bt-plan-msg",                "max-width" => "100%"),
        # Hide the cwd path in the header — not enough room
        CSS(".bt-header-cwd", "display" => "none")),
)
