#!/usr/bin/env sh
# BonitoTeam worker installer — idempotent.
# Usage:    curl -fsSL {{SERVER_URL}}/install.sh | sh
# Re-runs:  same command — every step is "check / update / create".
#
# Layout after install:
#   ~/.local/share/bonitoteam/Project.toml    SINGLE operational Julia env
#   ~/.local/share/bonitoteam/Manifest.toml   resolved deps (generated)
#   ~/.local/share/bonitoteam/BonitoMCP/      source tree
#   ~/.local/share/bonitoteam/BonitoWorker/   source tree
#   ~/.local/share/bonitoteam/RemoteSync/     source tree
#   ~/.local/bin/{bonitoteam-worker,bonitoteam-mcp,bonitoteam-worker-start}
#   ~/.config/systemd/user/bonitoteam-worker.service
#   ~/bonitoteam-projects/                    rsync target for project sources
#
# Per-package Project.toml files (BonitoMCP/Project.toml etc.) are NEVER
# used as runtime envs — only the top-level $INSTALL_ROOT/Project.toml is.
set -eu

SERVER="{{SERVER_URL}}"
SECRET="{{WORKER_SECRET}}"
INSTALL_ROOT="$HOME/.local/share/bonitoteam"
MCP_DIR="$INSTALL_ROOT/BonitoMCP"
WORKER_DIR="$INSTALL_ROOT/BonitoWorker"
BIN_DIR="$HOME/.local/bin"
PROJECTS_ROOT="$HOME/bonitoteam-projects"

echo "==> BonitoTeam worker installer"
echo "    Server : $SERVER"

mkdir -p "$INSTALL_ROOT" "$BIN_DIR" "$PROJECTS_ROOT"

# ── Worker display name ──────────────────────────────────────────────────────
# The server keys workers by a stable per-install UUID (generated by the
# worker itself on first run). The display name is just a label — defaults to
# `$USER@$(hostname)` and is shown in the dashboard. You can rename it later
# from the UI; setting `BONITOTEAM_WORKER_NAME=…` here just seeds that label.
#
# We try to prompt from /dev/tty so curl|sh installs can still ask, falling
# back to the default if no terminal is attached (CI, devcontainer, etc.).
DEFAULT_NAME="${BONITOTEAM_WORKER_NAME:-$USER@$(hostname)}"
WORKER_NAME="$DEFAULT_NAME"
if [ -z "${BONITOTEAM_WORKER_NAME:-}" ] && [ -r /dev/tty ]; then
    printf '    Display name [%s]: ' "$DEFAULT_NAME" > /dev/tty
    if IFS= read -r entered < /dev/tty; then
        if [ -n "$entered" ]; then
            WORKER_NAME="$entered"
        fi
    fi
fi
echo "    Name   : $WORKER_NAME"

# Make user-local bins available for the rest of this script
export PATH="$BIN_DIR:$HOME/.juliaup/bin:$PATH"

step() { echo ""; echo "==> $*"; }

# ── Prerequisites: claude, claude-agent-acp, npm (user-managed) ──────────────
# We assume you've already installed and logged in to Claude Code via your usual
# means (e.g. `npm install -g @anthropic-ai/claude-code` + `claude login`). The
# installer only verifies they're on PATH.
step "Prerequisites in PATH"
missing=""
for bin in npm claude claude-agent-acp; do
    if command -v "$bin" > /dev/null 2>&1; then
        echo "    ok   : $bin -> $(command -v "$bin")"
    else
        echo "    MISS : $bin"
        missing="$missing $bin"
    fi
done
if [ -n "$missing" ]; then
    echo ""
    echo "ERROR: missing required binaries:$missing"
    echo "       Install with:"
    echo "         npm install -g @anthropic-ai/claude-code @agentclientprotocol/claude-agent-acp"
    echo "         claude login"
    exit 1
fi

# ── Julia (via juliaup) ───────────────────────────────────────────────────────
step "Julia"
if ! command -v juliaup > /dev/null 2>&1; then
    echo "    juliaup missing — installing..."
    curl -fsSL https://install.julialang.org | sh -s -- --yes
    export PATH="$HOME/.juliaup/bin:$PATH"
fi
if ! command -v julia > /dev/null 2>&1; then
    juliaup add lts && juliaup default lts
fi
echo "    julia: $(julia --version)"

# ── Worker bundle (BonitoMCP + BonitoWorker + RemoteSync source trees) ───────
step "Worker bundle"
TMP_TAR="$(mktemp -t bonitoteam-bundle.XXXXXX.tar.gz)"
trap 'rm -f "$TMP_TAR"' EXIT
echo "    fetching $SERVER/worker/bundle.tar.gz..."
curl -fsSL "$SERVER/worker/bundle.tar.gz" -o "$TMP_TAR"
tar -xzf "$TMP_TAR" -C "$INSTALL_ROOT"
chmod +x "$MCP_DIR/bin/"* "$WORKER_DIR/bin/"*
echo "    extracted to $INSTALL_ROOT"

# Single operational env at $INSTALL_ROOT/Project.toml. Both bin scripts
# (bonitoteam-worker, bonitoteam-mcp) compute --project as the parent of
# their package dir and land here, so we instantiate once.
step "Worker env Project.toml at $INSTALL_ROOT"
cat > "$INSTALL_ROOT/Project.toml" << 'TOML'
[deps]
BonitoMCP    = "4a1c91af-1c90-46a4-8594-a3846516869d"
BonitoWorker = "98909ed9-6989-4829-81af-73688ee23085"
RemoteSync   = "8d4f0e91-3a2b-4d6c-9e8f-1a2b3c4d5e6f"

[sources]
BonitoMCP    = {path = "BonitoMCP"}
BonitoWorker = {path = "BonitoWorker"}
RemoteSync   = {path = "RemoteSync"}

[compat]
julia = "1.10"
TOML
# Drop any stale Manifest.toml from a previous install — old Manifests can
# refer to packages or paths that no longer exist after an upgrade.
rm -f "$INSTALL_ROOT/Manifest.toml"
echo "    written"

step "Instantiate Julia env"
julia --project="$INSTALL_ROOT" --startup-file=no \
    -e 'import Pkg; Pkg.instantiate(); Pkg.precompile()'

# ── Wrappers + startup shim ──────────────────────────────────────────────────
step "Wrappers + startup shim"
ln -sf "$MCP_DIR/bin/bonitoteam-mcp"       "$BIN_DIR/bonitoteam-mcp"
ln -sf "$WORKER_DIR/bin/bonitoteam-worker" "$BIN_DIR/bonitoteam-worker"

cat > "$BIN_DIR/bonitoteam-worker-start" << 'STARTSCRIPT'
#!/usr/bin/env sh
export BONITOTEAM_WORKER_SECRET="__SECRET__"
export BONITOTEAM_SERVER_URL="${BONITOTEAM_SERVER_URL:-__SERVER__}"
export BONITOTEAM_WORKER_NAME="${BONITOTEAM_WORKER_NAME:-__WORKERNAME__}"
export BONITOTEAM_MCP_BIN="${BONITOTEAM_MCP_BIN:-__BINDIR__/bonitoteam-mcp}"
export BONITOTEAM_PROJECTS_ROOT="${BONITOTEAM_PROJECTS_ROOT:-__PROJROOT__}"
export PATH="$HOME/.juliaup/bin:$PATH"
exec "__BINDIR__/bonitoteam-worker"
STARTSCRIPT
sed -i.bak \
    -e "s@__SECRET__@$SECRET@g" \
    -e "s@__BINDIR__@$BIN_DIR@g" \
    -e "s@__PROJROOT__@$PROJECTS_ROOT@g" \
    -e "s@__SERVER__@$SERVER@g" \
    -e "s@__WORKERNAME__@$WORKER_NAME@g" \
    "$BIN_DIR/bonitoteam-worker-start"
rm -f "$BIN_DIR/bonitoteam-worker-start.bak"
chmod +x "$BIN_DIR/bonitoteam-worker-start"

# ── systemd user service: enable + start ─────────────────────────────────────
step "systemd user service"
if command -v systemctl > /dev/null 2>&1; then
    SVCDIR="$HOME/.config/systemd/user"
    mkdir -p "$SVCDIR"
    cat > "$SVCDIR/bonitoteam-worker.service" << SVCFILE
[Unit]
Description=BonitoTeam agent worker
After=network.target

[Service]
ExecStart=$BIN_DIR/bonitoteam-worker-start
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
SVCFILE
    systemctl --user daemon-reload
    systemctl --user enable bonitoteam-worker > /dev/null 2>&1 || true
    systemctl --user restart bonitoteam-worker
    sleep 1
    if systemctl --user is-active --quiet bonitoteam-worker; then
        echo "    bonitoteam-worker.service: active"
    else
        echo "    bonitoteam-worker.service failed to start. Check: journalctl --user -u bonitoteam-worker -e"
    fi
else
    echo "    no systemctl — start manually: $BIN_DIR/bonitoteam-worker-start"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "==> Installation complete."
echo "    The worker holds an outbound WebSocket to $SERVER — no inbound port,"
echo "    no firewall rules needed on this machine. It appears in the dashboard"
echo "    as soon as the connection is up."
